package com.accdatos.tema5;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AccesoADatosTema5Application {

    public static void main(String[] args) {
        SpringApplication.run(AccesoADatosTema5Application.class, args);
    }
}
